
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 20 09:50:35 CET 2018
//----------------------------------------------------

package parserClasses;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 40;
  public static final int INT32 = 10;
  public static final int UNIT = 16;
  public static final int LOWER = 34;
  public static final int LOWEREQUAL = 35;
  public static final int MINUS = 38;
  public static final int NOT = 37;
  public static final int SEMICOLON = 30;
  public static final int AND = 32;
  public static final int RPAR = 28;
  public static final int IN = 9;
  public static final int BOOL = 2;
  public static final int COMMA = 31;
  public static final int CLASS = 3;
  public static final int OBJECTIDENTIFIER = 23;
  public static final int DIV = 36;
  public static final int PLUS = 39;
  public static final int ASSIGN = 18;
  public static final int IF = 8;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int EQUAL = 33;
  public static final int TRUE = 15;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int ISNULL = 11;
  public static final int INTEGERLITERAL = 24;
  public static final int TIMES = 41;
  public static final int COLON = 29;
  public static final int LBRACE = 25;
  public static final int ELSE = 5;
  public static final int WHILE = 17;
  public static final int LET = 12;
  public static final int THEN = 14;
  public static final int RBRACE = 26;
  public static final int EXTENDS = 6;
  public static final int LPAR = 27;
  public static final int STRING = 20;
  public static final int STRINGLITERAL = 21;
  public static final int TYPEIDENTIFIER = 22;
  public static final int FALSE = 7;
  public static final int DO = 4;
}

